---
:url: http://farm8.static.flickr.com/7063/7141494779_5f05414e3d.jpg
:real_name: ''
:title: Fancy a Cuppa?
:url_photopage: http://www.flickr.com/photos/nlireland/7141494779/
:username: National Library of Ireland on The Commons
:taken_at: 1910-05-04 10:56:40.000000000 -05:00
:license_name: No known copyright restrictions
:license_url: http://www.flickr.com/commons/usage/
