---
:url: http://farm3.static.flickr.com/2656/5820866907_336d18627e.jpg
:real_name: paul (dex) bica
:title: end of the day
:url_photopage: http://www.flickr.com/photos/dexxus/5820866907/
:username: paul bica
:taken_at: 2011-02-09 23:26:52.000000000 -05:00
:license_name: Attribution License
:license_url: http://creativecommons.org/licenses/by/2.0/
