---
:url: http://farm4.static.flickr.com/3418/5812081550_d55a8ac5b8.jpg
:real_name: Jean-Daniel Echenard
:title: Cygne,Confort et chaleur
:url_photopage: http://www.flickr.com/photos/34804353@N02/5812081550/
:username: jd.echenard
:taken_at: 2011-06-07 16:32:52.000000000 +10:00
:license_name: Attribution-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nd/2.0/
