---
:url: http://farm9.static.flickr.com/8428/7530054972_576f6e2b22.jpg
:real_name: ''
:title: Drops On Bright Orange Flower
:url_photopage: http://www.flickr.com/photos/80901381@N04/7530054972/
:username: A Guy Taking Pictures
:taken_at: 2012-07-06 10:36:34.000000000 +10:00
:license_name: Attribution License
:license_url: http://creativecommons.org/licenses/by/2.0/
