---
:url: http://farm7.static.flickr.com/6175/6176698785_7dee72237e.jpg
:real_name: ''
:title: Hubbard Glacier - Alaska
:url_photopage: http://www.flickr.com/photos/blmiers2/6176698785/
:username: blmiers2
:taken_at: 2011-08-25 11:26:59.000000000 -04:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
