---
:url: http://farm8.static.flickr.com/7078/7352069826_1e667da00b.jpg
:real_name: ''
:title: Happy Caturday to all friends !
:url_photopage: http://www.flickr.com/photos/aoa-/7352069826/
:username: Viola & Cats =^..^= HAPPY HOLIDAY !
:taken_at: 2012-06-08 09:14:46.000000000 +00:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
