---
:url: http://farm8.static.flickr.com/7130/7680433672_80f0b08a6a.jpg
:real_name: ''
:title: Sunset Reflection
:url_photopage: http://www.flickr.com/photos/jeff_sch/7680433672/
:username: Jeff S. PhotoArt
:taken_at: 2012-07-30 16:51:33.000000000 +00:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
