---
:url: http://farm7.static.flickr.com/6035/6333877960_41936fc5ba.jpg
:real_name: ''
:title: Winter bird in the snow
:url_photopage: http://www.flickr.com/photos/blmiers2/6333877960/
:username: blmiers2
:taken_at: 2007-02-14 12:06:12.000000000 -05:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
