---
:url: http://farm7.static.flickr.com/6049/6250538830_78d4ccaa01.jpg
:real_name: ''
:title: Nature - Animal - Wildlife - White White-tailed Deer
:url_photopage: http://www.flickr.com/photos/blmiers2/6250538830/
:username: blmiers2
:taken_at: 2011-10-16 09:02:59.000000000 -04:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
