---
:url: http://farm7.static.flickr.com/6225/6338141481_ff6b922312.jpg
:real_name: ''
:title: Animal - Grizzly Bear - Alaska
:url_photopage: http://www.flickr.com/photos/blmiers2/6338141481/
:username: blmiers2
:taken_at: 2011-08-27 14:28:27.000000000 -04:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
