---
:url: http://farm7.static.flickr.com/6081/6125779338_ae4467236f.jpg
:real_name: ''
:title: Denali Rainshower - Alaska -  Mountains
:url_photopage: http://www.flickr.com/photos/blmiers2/6125779338/
:username: blmiers2
:taken_at: 2011-08-27 18:46:52.000000000 -04:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
