---
:url: http://farm6.static.flickr.com/5066/5689595852_70c434353a.jpg
:real_name: Neil  Kremer
:title: Rocketship Park
:url_photopage: http://www.flickr.com/photos/neilarmstrong2/5689595852/
:username: Neil Kremer
:taken_at: 2011-05-04 19:59:59.000000000 -04:00
:license_name: Attribution-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nd/2.0/
