---
:url: http://farm9.static.flickr.com/8498/8389314423_2464403123.jpg
:real_name: Dominik
:title: ! 'Their Majesties [Explored #12]'
:url_photopage: http://www.flickr.com/photos/sibilus_basilea/8389314423/
:username: Sibilus_Basilea
:taken_at: 2013-01-12 17:21:15.000000000 +00:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
