---
:url: http://farm7.static.flickr.com/6109/6338385848_c1393cac48.jpg
:real_name: Mike
:title: foxbat
:url_photopage: http://www.flickr.com/photos/pmiaki/6338385848/
:username: psiaki
:taken_at: 2011-11-12 16:33:34.000000000 -05:00
:license_name: Attribution License
:license_url: http://creativecommons.org/licenses/by/2.0/
