---
:url: http://farm8.static.flickr.com/7159/6834862369_da8e4f7a26.jpg
:real_name: Vinoth Chandar
:title: The Beast in the Bush
:url_photopage: http://www.flickr.com/photos/vinothchandar/6834862369/
:username: VinothChandar
:taken_at: 2011-08-27 07:57:10.000000000 +10:00
:license_name: Attribution License
:license_url: http://creativecommons.org/licenses/by/2.0/
