---
:url: http://farm8.static.flickr.com/7191/6904758951_6868a06560.jpg
:real_name: ''
:title: Denali - Mountain Landscape from Alaska
:url_photopage: http://www.flickr.com/photos/blmiers2/6904758951/
:username: blmiers2
:taken_at: 2011-08-27 13:34:29.000000000 -04:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
