---
:url: http://farm8.static.flickr.com/7008/6733322351_d40c2242b0.jpg
:real_name: ''
:title: Frosty Footpath - winter snow
:url_photopage: http://www.flickr.com/photos/blmiers2/6733322351/
:username: blmiers2
:taken_at: 2012-01-14 14:22:28.000000000 -05:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
