---
:url: http://farm6.static.flickr.com/5034/5910467818_d228741c08.jpg
:real_name: Filippo Bianchi
:title: Kampa Island
:url_photopage: http://www.flickr.com/photos/fibia/5910467818/
:username: Fil.ippo (busy)
:taken_at: 2011-05-26 18:17:10.000000000 +00:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
