---
:url: http://farm6.static.flickr.com/5189/5652914929_80691fe627.jpg
:real_name: paul (dex) bica
:title: waipio
:url_photopage: http://www.flickr.com/photos/dexxus/5652914929/
:username: paul bica
:taken_at: 2011-01-27 16:25:24.000000000 -05:00
:license_name: Attribution License
:license_url: http://creativecommons.org/licenses/by/2.0/
