---
:url: http://farm9.static.flickr.com/8142/7316852406_2e131b6277.jpg
:real_name: ''
:title: Happy Caturday (Saturday) to all Flickr friends !
:url_photopage: http://www.flickr.com/photos/aoa-/7316852406/
:username: Viola & Cats =^..^=
:taken_at: 2012-05-29 13:30:32.000000000 +00:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
