---
:url: http://farm7.static.flickr.com/6052/6293388936_d55ba13c4e.jpg
:real_name: ''
:title: Autumn trees
:url_photopage: http://www.flickr.com/photos/blmiers2/6293388936/
:username: blmiers2
:taken_at: 2010-11-06 15:04:47.000000000 -04:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
