---
:url: http://farm7.static.flickr.com/6151/6159637428_6bffb5bce1.jpg
:real_name: ''
:title: Misty Morning Sunrise - Alaska Landscape
:url_photopage: http://www.flickr.com/photos/blmiers2/6159637428/
:username: blmiers2
:taken_at: 2011-08-20 10:56:18.000000000 -04:00
:license_name: Attribution-NonCommercial-ShareAlike License
:license_url: http://creativecommons.org/licenses/by-nc-sa/2.0/
