---
:url: http://farm7.static.flickr.com/6080/6058753775_b1af6198ba.jpg
:real_name: Joe Penniston
:title: Disney Dining Under the Sea (Explored)
:url_photopage: http://www.flickr.com/photos/expressmonorail/6058753775/
:username: Express Monorail
:taken_at: 2010-12-06 10:00:32.000000000 +10:00
:license_name: Attribution-NonCommercial-NoDerivs License
:license_url: http://creativecommons.org/licenses/by-nc-nd/2.0/
