---
:url: http://farm6.static.flickr.com/5030/5621252335_094cd5f88c.jpg
:real_name: paul (dex) bica
:title: napali
:url_photopage: http://www.flickr.com/photos/dexxus/5621252335/
:username: paul bica
:taken_at: 2011-02-09 15:18:32.000000000 -05:00
:license_name: Attribution License
:license_url: http://creativecommons.org/licenses/by/2.0/
